"""Generator framework: abstract base and registry.

Generators read ONLY from CommonModel. They never inspect raw source CLI.
Adding a new target vendor does not require changing any parser.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from typing import Callable

from model.enums import SECTION_ORDER, SectionType, Vendor
from model.objects import CommonModel, GeneratedSection

logger = logging.getLogger(__name__)


class GenerateResult:
    def __init__(
        self,
        full_config: str,
        sections: list[GeneratedSection],
        vendor: Vendor,
        warnings: list[dict] | None = None,
    ) -> None:
        self.full_config = full_config
        self.sections = sections
        self.vendor = vendor
        self.warnings = warnings or []


class SectionGenerator(ABC):
    section_type: SectionType

    @abstractmethod
    def generate(self, model: CommonModel) -> GeneratedSection:
        """Emit target-vendor syntax for one section from the common model."""


class VendorGenerator(ABC):
    vendor: Vendor

    def __init__(self) -> None:
        self.section_generators: list[SectionGenerator] = self.build_section_generators()

    @abstractmethod
    def build_section_generators(self) -> list[SectionGenerator]:
        ...

    def header(self, model: CommonModel) -> str:
        return (
            f"# Generated by Firewall Migration Platform\n"
            f"# Target: {self.vendor.display_name}\n"
            f"# Source vendor: {model.source_vendor}\n"
            f"# Hostname: {model.hostname or 'unknown'}\n"
            f"# Total objects: {model.total_objects()}\n\n"
        )

    def generate(self, model: CommonModel) -> GenerateResult:
        sections: list[GeneratedSection] = []
        warnings: list[dict] = []
        parts: list[str] = [self.header(model)]

        for sg in self.section_generators:
            try:
                section = sg.generate(model)
                sections.append(section)
                if section.content.strip():
                    parts.append(f"\n# === {section.display_name} ===\n")
                    parts.append(section.content)
                    if not section.content.endswith("\n"):
                        parts.append("\n")
                if not section.success:
                    for err in section.errors:
                        warnings.append(
                            {
                                "code": "GENERATE_SECTION_ERROR",
                                "message": err,
                                "section": section.section_type,
                                "severity": "warning",
                            }
                        )
            except Exception as exc:  # noqa: BLE001
                logger.exception("Section generator %s failed", sg.section_type)
                sections.append(
                    GeneratedSection(
                        section_type=sg.section_type.value,
                        display_name=sg.section_type.display_name,
                        content="",
                        object_count=0,
                        success=False,
                        errors=[str(exc)],
                    )
                )
                warnings.append(
                    {
                        "code": "GENERATE_SECTION_EXCEPTION",
                        "message": f"Failed to generate {sg.section_type.display_name}: {exc}",
                        "section": sg.section_type.value,
                        "severity": "error",
                    }
                )

        present = {s.section_type for s in sections}
        for st in SECTION_ORDER:
            if st.value not in present:
                sections.append(
                    GeneratedSection(
                        section_type=st.value,
                        display_name=st.display_name,
                        content="",
                        object_count=0,
                        success=True,
                    )
                )

        order_map = {st.value: i for i, st in enumerate(SECTION_ORDER)}
        sections.sort(key=lambda s: order_map.get(s.section_type, 999))

        return GenerateResult(
            full_config="".join(parts),
            sections=sections,
            vendor=self.vendor,
            warnings=warnings,
        )


_GENERATOR_REGISTRY: dict[Vendor, type[VendorGenerator]] = {}


def register_generator(vendor: Vendor) -> Callable[[type[VendorGenerator]], type[VendorGenerator]]:
    def decorator(cls: type[VendorGenerator]) -> type[VendorGenerator]:
        cls.vendor = vendor
        _GENERATOR_REGISTRY[vendor] = cls
        return cls

    return decorator


def get_generator(vendor: Vendor) -> VendorGenerator:
    if vendor not in _GENERATOR_REGISTRY:
        raise KeyError(f"No generator registered for vendor: {vendor}")
    return _GENERATOR_REGISTRY[vendor]()


def list_generators() -> list[Vendor]:
    return list(_GENERATOR_REGISTRY.keys())


def ensure_generators_loaded() -> None:
    from generator import fortigate as _fg  # noqa: F401
    from generator import palo as _pa  # noqa: F401
    from generator import checkpoint as _cp  # noqa: F401
    from generator import ftd as _ftd  # noqa: F401
