"""Cisco FTD target configuration generator."""

from __future__ import annotations

from model.enums import SectionType, Vendor
from model.objects import CommonModel, GeneratedSection
from generator.base import SectionGenerator, VendorGenerator, register_generator
from generator.common import default_stub_generators


class FTDAddressGen(SectionGenerator):
    section_type = SectionType.ADDRESSES

    def generate(self, model: CommonModel) -> GeneratedSection:
        lines: list[str] = []
        for addr in model.addresses:
            lines.append(f"object network {addr.name}")
            if addr.address_type.value == "fqdn":
                lines.append(f" fqdn {addr.value}")
            elif "-" in addr.value and "/" not in addr.value:
                start, end = addr.value.split("-", 1)
                lines.append(f" range {start} {end}")
            elif "/" in addr.value:
                ip, mask = addr.value.split("/", 1)
                lines.append(f" subnet {ip} {mask}")
            else:
                lines.append(f" host {addr.value}")
        content = "\n".join(lines) if lines else "# (no addresses)"
        return GeneratedSection(
            section_type=self.section_type.value,
            display_name=self.section_type.display_name,
            content=content,
            object_count=len(model.addresses),
            success=True,
        )


class FTDServiceGen(SectionGenerator):
    section_type = SectionType.SERVICES

    def generate(self, model: CommonModel) -> GeneratedSection:
        lines: list[str] = []
        for svc in model.services:
            lines.append(f"object service {svc.name}")
            ports = " ".join(svc.destination_ports) or "0"
            proto = svc.protocol.value
            if proto in ("tcp", "udp"):
                lines.append(f" service {proto} destination eq {ports}")
            else:
                lines.append(f" service {proto}")
        content = "\n".join(lines) if lines else "# (no services)"
        return GeneratedSection(
            section_type=self.section_type.value,
            display_name=self.section_type.display_name,
            content=content,
            object_count=len(model.services),
            success=True,
        )


class FTDPolicyGen(SectionGenerator):
    section_type = SectionType.FIREWALL_POLICIES

    def generate(self, model: CommonModel) -> GeneratedSection:
        lines: list[str] = ["access-list MIGRATED_ACL extended remark Generated by FWM"]
        for pol in model.policies:
            action = "permit" if pol.action.value == "allow" else "deny"
            src = " ".join(r.name for r in pol.source_addresses) or "any"
            dst = " ".join(r.name for r in pol.destination_addresses) or "any"
            svc = " ".join(r.name for r in pol.services) or "ip"
            # Simplified ACL form – full FTD policy uses ACP rules in FMC
            lines.append(
                f"access-list MIGRATED_ACL extended {action} object-group {svc} "
                f"object-group {src} object-group {dst}  # {pol.name}"
            )
        content = "\n".join(lines) if model.policies else "# (no policies)"
        return GeneratedSection(
            section_type=self.section_type.value,
            display_name=self.section_type.display_name,
            content=content,
            object_count=len(model.policies),
            success=True,
        )


class FTDInterfaceGen(SectionGenerator):
    section_type = SectionType.INTERFACES

    def generate(self, model: CommonModel) -> GeneratedSection:
        lines: list[str] = []
        for iface in model.interfaces:
            lines.append(f"interface {iface.name}")
            if iface.ip_addresses:
                lines.append(
                    f" ip address {iface.ip_addresses[0]} {iface.netmask or '255.255.255.0'}"
                )
            lines.append(f" nameif {iface.zone or iface.name}")
            lines.append(" security-level 0")
            if not iface.enabled:
                lines.append(" shutdown")
        content = "\n".join(lines) if lines else "# (no interfaces)"
        return GeneratedSection(
            section_type=self.section_type.value,
            display_name=self.section_type.display_name,
            content=content,
            object_count=len(model.interfaces),
            success=True,
        )


@register_generator(Vendor.CISCO_FTD)
class CiscoFTDGenerator(VendorGenerator):
    vendor = Vendor.CISCO_FTD

    def build_section_generators(self) -> list[SectionGenerator]:
        specialized = {
            SectionType.INTERFACES: FTDInterfaceGen(),
            SectionType.ADDRESSES: FTDAddressGen(),
            SectionType.SERVICES: FTDServiceGen(),
            SectionType.FIREWALL_POLICIES: FTDPolicyGen(),
        }
        result: list[SectionGenerator] = []
        for gen in default_stub_generators(line_prefix="!"):
            if gen.section_type in specialized:
                result.append(specialized[gen.section_type])
            else:
                result.append(gen)
        return result
